all: q1 q2 q3 q4p1 q4p2

q1: q1.c
	gcc -o q1 q1.c

q2: q2.c
	gcc -o q2 q2.c

q3: q3.c
	gcc -o q3 q3.c

q4p1: q4p1.c
	gcc -o q4p1 q4p1.c

q4p2: q4p2.c
	gcc -o q4p2 q4p2.c

clean:
	rm -f q1 q2 q3 q4p1 q4p2