all: list countw copy move main

list: list.c
	gcc -o list list.c

countw: countw.c
	gcc -o countw countw.c

copy: copy.c
	gcc -o copy copy.c

move: move.c
	gcc -o move move.c

main: main.c
	gcc -o main main.c

clean:
	rm -f list countw copy move main
